version: '3.8'
services:
  grpc-server:
    build: .
    ports:
      - "50051:50051"
    volumes:
      - type: volume
        source: image_database_volume
        target: /app/image_database
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  image_database_volume:
