// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: image_search.proto

package grpc_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageSearchServiceClient is the client API for ImageSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageSearchServiceClient interface {
	// Sends a search request to the server.
	SearchImage(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type imageSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageSearchServiceClient(cc grpc.ClientConnInterface) ImageSearchServiceClient {
	return &imageSearchServiceClient{cc}
}

func (c *imageSearchServiceClient) SearchImage(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/imagesearch.ImageSearchService/SearchImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageSearchServiceServer is the server API for ImageSearchService service.
// All implementations must embed UnimplementedImageSearchServiceServer
// for forward compatibility
type ImageSearchServiceServer interface {
	// Sends a search request to the server.
	SearchImage(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedImageSearchServiceServer()
}

// UnimplementedImageSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageSearchServiceServer struct {
}

func (UnimplementedImageSearchServiceServer) SearchImage(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchImage not implemented")
}
func (UnimplementedImageSearchServiceServer) mustEmbedUnimplementedImageSearchServiceServer() {}

// UnsafeImageSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageSearchServiceServer will
// result in compilation errors.
type UnsafeImageSearchServiceServer interface {
	mustEmbedUnimplementedImageSearchServiceServer()
}

func RegisterImageSearchServiceServer(s grpc.ServiceRegistrar, srv ImageSearchServiceServer) {
	s.RegisterService(&ImageSearchService_ServiceDesc, srv)
}

func _ImageSearchService_SearchImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageSearchServiceServer).SearchImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imagesearch.ImageSearchService/SearchImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageSearchServiceServer).SearchImage(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageSearchService_ServiceDesc is the grpc.ServiceDesc for ImageSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imagesearch.ImageSearchService",
	HandlerType: (*ImageSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchImage",
			Handler:    _ImageSearchService_SearchImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "image_search.proto",
}
